name: flutter_result
description: "A simple and extensible Result-based architecture for handling success and failure in Flutter apps."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
